{{- if and .Values.config.enabled .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-scan-adapter.configMapName" . }}
  labels:
    {{- include "paperless-scan-adapter.labels" . | nindent 4 }}
    {{- with .Values.config.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
