apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-scan-adapter.fullname" . }}
  labels:
    {{- include "paperless-scan-adapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paperless-scan-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paperless-scan-adapter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "paperless-scan-adapter.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- $useConfigMap := and .Values.config.enabled .Values.config.data }}
          {{- if or $useConfigMap .Values.env.extraEnvFrom }}
          envFrom:
            {{- if $useConfigMap }}
            - configMapRef:
                name: {{ include "paperless-scan-adapter.configMapName" . }}
            {{- end }}
            {{- range .Values.env.extraEnvFrom }}
            - {{- if .configMapRef }}
              configMapRef:
                name: {{ .configMapRef.name }}
                {{- if hasKey .configMapRef "optional" }}
                optional: {{ .configMapRef.optional }}
                {{- end }}
            {{- else if .secretRef }}
              secretRef:
                name: {{ .secretRef.name }}
                {{- if hasKey .secretRef "optional" }}
                optional: {{ .secretRef.optional }}
                {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if or .Values.env.extraEnv .Values.env.secretRefs }}
          env:
            {{- range .Values.env.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.env.secretRefs }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
                  {{- if hasKey . "optional" }}
                  optional: {{ .optional }}
                  {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.persistence.enabled .Values.volumeMounts }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.persistence.enabled .Values.volumes }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "paperless-scan-adapter.pvcName" . }}
      {{- end }}
      {{- with .Values.volumes }}
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
